version: "3.9"
services:
  app:
    build: .
    command: [ 'dockerize', '-wait', 'tcp://db:5432', './commands.sh' ]
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - "data:/var/lib/postgresql/data"
    env_file:
      - .env
volumes:
  data:
